name: TheDarkness
version: 0.1
authors: [Arzeyt, Malikk]
main: us.twoguys.thedarkness.TheDarkness
softdepend: [Shield]
commands:
    giveBeacon:
        description: Gives beacons to a player
        usage: /giveBeacon <playerName> <amount>
    beaconStats:
        description: Shows beacon stats
        usage: /beaconStats
    darkreload:
        description: Reloads the config file
        usage: /darkreload
    beaconSight:
        description: allows you to see beacons
        usage: /beaconSight
    createBeacon:
        description: creates a beacon at your location
        usage: /creatBeacon
    theDarkness:
        description: basic command
        usage: /theDarkness 
        aliases: [darkness, td, dark]